play_preset:
  name: Play Preset
  target:
    entity:
      integration: linkplay
      domain: media_player
  fields:
    preset_number:
      example: 1
      required: true
      default: 1
      selector:
        number:
          min: 1
          max: 10
          mode: box

send_command:
  name: HTTP API Command
  description: Execute HTTP API linkplay-specific commands on the player. Be careful! Some commands can cause damage to your device if you don't know what you're doing.
  target:
    entity:
      integration: linkplay
      domain: media_player
  fields:
    command:
      description: The raw HTTP command to send to the LinnkPlay device
      example: Update
      required: true
      selector:
        text:
